services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Bash\S365ContentBundle\Domain\HttpClient\ContentClientInterface:
        alias: Bash\S365ContentBundle\Infrastructure\HttpClient\ContentClient

    Bash\S365ContentBundle\Infrastructure\HttpClient\ContentClient:
        tags:
            - { name: monolog.logger, channel: s365_content }

    Bash\S365ContentBundle\Infrastructure\HttpClient\ContentAuthenticator:
        arguments:
            $cache: '@cache.app'

    Bash\S365ContentBundle\Infrastructure\Symfony\Controller\:
        resource: '../../Infrastructure/Symfony/Controller/'
        public: true
        tags: ['controller.service_arguments']
